# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180226_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='image',
        ),
    ]
