# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180228_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание выставки'),
        ),
        migrations.AddField(
            model_name='exposition',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата окончания'),
        ),
    ]
